/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mnessim;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String command = "cat";
        ArgParser p = new ArgParser(command);
        debugPrint(p);

        String commandAndFlag = "cat -afde";
        ArgParser p2 = new ArgParser(commandAndFlag);
        debugPrint(p2);

        try {
            String resp = Fetcher.httpGet("https://api.chess.com/pub/player/tenderllama");
            System.out.println(resp);
        } catch (java.io.IOException e) {
            System.err.println(e.getMessage());
        }
    }

    private static void debugPrint(ArgParser p) {
        String c = p.getCommand();
        char[] f = p.getFlags();
        String[] a = p.getArguments();
        System.out.print("C: " + c + " F: [");
        if (f != null) {
            for (int i = 0; i < f.length; i++) {
            System.out.print(f[i]);
            if (i < f.length - 1) System.out.print(", ");
            }
        }
        System.out.print("] A: [");
        if (a != null) {
            for (int i = 0; i < a.length; i++) {
            System.out.print(a[i]);
            if (i < a.length - 1) System.out.print(", ");
            }
        }
        System.out.println("]");
    }
}
